[tool.poetry]
name = "klingo"
version = "0.1.0"
description = "A minimal framework for creating parameterized airfoil geometries."
authors = ["Gabriel B. Santos <gabriel.bertacco@unesp.br>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/gabrielbdsantos/klingo"
keywords = ["blade", "airfoil", "parameterization"]

[tool.poetry.dependencies]
python = ">=3.7,<3.10"
numpy = "^1.21.5"
scipy = "^1.7.3"
numpy-stl = "^2.16.3"

[tool.poetry.dev-dependencies]
ipykernel = "^6.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79

[tool.pydocstyle]
# Numpy style + D105
ignore = "D105,D107,D203,D212,D213,D402,D413,D415,D416,D417"
