[tool.poetry]
name = 'klingo'
version = '0.1.0-beta'
description = 'A minimal framework for creating parameterized airfoil geometries.'
authors = ['Gabriel B. Santos <gabriel.bertacco@unesp.br>']
license = 'MIT'
readme = 'README.md'
repository = 'https://github.com/gabrielbdsantos/klingo'
keywords = ['blade', 'airfoil', 'parameterization']

[tool.poetry.dependencies]
python = '>=3.8,<3.10'
numpy = '>=1.20'
scipy = '>=1.7'
numpy-stl = "^2.16.3"

[tool.poetry.dev-dependencies]
ipykernel = "^6.6.0"

[build-system]
requires = ['poetry-core>=1.0.0']
build-backend = 'poetry.core.masonry.api'

[tool.black]
line-length = 79

[tool.pydocstyle]
convention = 'numpy'
