[tool.poetry]
name = 'klingo'
version = '0.1.0-beta'
description = 'A minimal framework for creating parameterized airfoil geometries.'
authors = ['Gabriel B. Santos <gabriel.bertacco@unesp.br>']
license = 'MIT'
readme = 'README.md'
repository = 'https://github.com/gabrielbdsantos/klingo'
keywords = ['blade', 'airfoil', 'parameterization', 'opencascade', 'occ']

[tool.poetry.dependencies]
python = '>=3.8,<3.10'
numpy = '>=1.20'
scipy = '>=1.7'
pythonocc-core = {git = 'https://github.com/tpaviot/pythonocc-core.git', tag = '7.5.1'}

[tool.poetry.dev-dependencies]
black = '*'
pylint = '*'
isort = '*'
pydocstyle = '*'

[build-system]
requires = ['poetry-core>=1.0.0']
build-backend = 'poetry.core.masonry.api'

[tool.black]
line-length = 79

[tool.pydocstyle]
convention = 'numpy'

[tool.pylint.basic]
variable-naming-style = 'any'  # please, do not complain about naming style.

[tool.pylint.master]
jobs = 4

[tool.pylint.messages_control]
disable = [
  'raw-checker-failed',
  'bad-inline-option',
  'locally-disabled',
  'file-ignored',
  'suppressed-message',
  'useless-suppression',
  'deprecated-pragma',
  'use-symbolic-message-instead',
  'too-many-arguments',
  'too-many-locals',
  'too-many-statements',
  'arguments-differ',
]
